import type { Metadata } from 'next'
import { site } from '@/content/site'

/**
 * ---------------------------------------------------------------------------
 * SEO metadata helper — shared by every page in the app.
 *
 * Open Graph image:
 *   Served by app/opengraph-image.tsx via the Next.js ImageResponse API at
 *   /opengraph-image (1200 × 630 px, image/png, edge-cached).
 *   Referenced here as an absolute URL so it works on all platforms
 *   (WhatsApp, LinkedIn, Facebook, Twitter/X) that require fully-qualified
 *   image URLs in og:image meta tags.
 *
 * Twitter card:
 *   Now `summary_large_image` — the OG image is available so the larger
 *   card variant is correct. Downgrading to `summary` was a temporary
 *   measure (noted in the original comment) until artwork existed.
 *
 * JSON-LD (`Organization`, `SoftwareApplication`, `FAQPage`, …) — Phase 10,
 *   once the facts each schema needs are signed off. Partial structured data
 *   is a liability, not a head start.
 * ---------------------------------------------------------------------------
 */

export const SITE_ORIGIN = site.url

/** Absolute URL to the default OG image. Generated by app/opengraph-image.tsx. */
export const OG_IMAGE_URL = `${SITE_ORIGIN}/opengraph-image`

/** Standard OG image dimensions (matches the ImageResponse size export). */
const OG_IMAGE_WIDTH = 1200
const OG_IMAGE_HEIGHT = 630

type PageMetadataInput = {
  title: string
  description?: string
  /** Root-relative path, e.g. `/pricing`. Used for the canonical URL. */
  path: string
  /** Set for pages that must never be indexed (scaffolding, internal tooling). */
  noIndex?: boolean
}

export function pageMetadata({
  title,
  description = site.description,
  path,
  noIndex = false,
}: PageMetadataInput): Metadata {
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      title,
      description,
      url: path,
      siteName: site.name,
      type: 'website',
      locale: 'en_IN',
      images: [
        {
          url: OG_IMAGE_URL,
          width: OG_IMAGE_WIDTH,
          height: OG_IMAGE_HEIGHT,
          alt: `${site.name} — Cloud RADIUS & ISP Management Platform`,
          type: 'image/png',
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [OG_IMAGE_URL],
    },
    ...(noIndex ? { robots: { index: false, follow: false } } : {}),
  }
}
