/**
 * ---------------------------------------------------------------------------
 * Calendar provider abstraction — Phase 8 integration interface.
 *
 * Contract (from .env.example):
 *   GOOGLE_CALENDAR_ID + GOOGLE_SERVICE_ACCOUNT_EMAIL +
 *   GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY present → live Google Calendar path
 *   Any credential absent                       → deterministic mock provider
 *
 * The slot picker in contact-content.tsx currently renders three static date
 * labels ("Tomorrow", "In 2 Days", "Next Monday") and four IST time slots
 * from content/contact.ts. The mock provider preserves this deterministic
 * behaviour so the UI works identically in demo mode.
 *
 * When Google Calendar credentials are available, replace `bookLive()` and
 * `getAvailabilityLive()` with real Google Calendar API calls. The interface
 * (CalendarBookingRequest in, CalendarBookingResult out) must not change so
 * that the API route is untouched.
 * ---------------------------------------------------------------------------
 */

export type CalendarBookingRequest = {
  /** Booker's display name. */
  name: string
  /** Booker's email — receives the invite in the live path. */
  email: string
  /** Company or ISP name — included in the event title. */
  company: string
  /**
   * Date label from the slot picker ("Tomorrow" | "In 2 Days" | "Next Monday").
   * Replaced with a real ISO date string when Google Calendar is integrated.
   */
  date: string
  /** IST time slot string, e.g. "10:00 AM IST". */
  slot: string
}

export type CalendarBookingResult =
  | {
      ok: true
      mode: 'live'
      /** Google Calendar event ID — available for cancellation / rescheduling. */
      eventId: string
      /** Google Meet URL generated by the Calendar API. */
      meetUrl: string
      /** ISO 8601 datetime string for the booked slot in IST (UTC+5:30). */
      startsAt: string
    }
  | {
      ok: true
      mode: 'demo'
      reason: string
      /** Placeholder — real Meet links are only generated in live mode. */
      meetUrl: null
    }
  | {
      ok: false
      mode: 'live' | 'demo'
      error: string
    }

/**
 * Check whether all three required Google Calendar credentials are present.
 */
function isCalendarConfigured(): boolean {
  return (
    typeof process.env['GOOGLE_CALENDAR_ID'] === 'string' &&
    process.env['GOOGLE_CALENDAR_ID'].length > 0 &&
    typeof process.env['GOOGLE_SERVICE_ACCOUNT_EMAIL'] === 'string' &&
    process.env['GOOGLE_SERVICE_ACCOUNT_EMAIL'].length > 0 &&
    typeof process.env['GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY'] === 'string' &&
    process.env['GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY'].length > 0
  )
}

/**
 * Live booking path — called only when all three credentials are present.
 *
 * PROVIDER PLUG-IN POINT: replace the body of this function with the
 * Google Calendar API call. Required steps:
 *   1. Parse the date label into a real calendar date in IST (UTC+5:30).
 *   2. Parse the slot string into a start time.
 *   3. Create a 30-minute Google Calendar event with conferenceData (Meet).
 *   4. Send invite to request.email.
 *   5. Return eventId, meetUrl, startsAt.
 *
 * Packages needed (not yet installed — add when implementing this step):
 *   npm install googleapis
 */
async function bookLive(
  _request: CalendarBookingRequest,
): Promise<CalendarBookingResult> {
  return {
    ok: false,
    mode: 'live',
    error:
      'Google Calendar credentials are set but the live integration has not ' +
      'been implemented yet. Implement bookLive() in lib/calendar/provider.ts ' +
      'to complete Phase 8 Step 3.',
  }
}

/**
 * Book a demo slot.
 *
 * Behaviour:
 * - Credentials absent  → returns a DEMO result immediately (no network call)
 * - Credentials present → delegates to bookLive()
 *
 * DEMO mode returns `meetUrl: null` explicitly — the UI must not fabricate
 * a Meet URL or imply that a real calendar event was created.
 */
export async function bookDemoSlot(
  request: CalendarBookingRequest,
): Promise<CalendarBookingResult> {
  if (!isCalendarConfigured()) {
    console.log(
      '[calendar:demo] Credentials absent. Would book slot:',
      request.date,
      request.slot,
      '| Booker:',
      request.email,
    )
    return {
      ok: true,
      mode: 'demo',
      reason:
        'GOOGLE_CALENDAR_ID, GOOGLE_SERVICE_ACCOUNT_EMAIL, and ' +
        'GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY are not configured. ' +
        'No calendar event was created and no Google Meet link was generated.',
      meetUrl: null,
    }
  }

  return bookLive(request)
}

/**
 * Returns the available time slots for a given date label.
 *
 * In demo mode this mirrors the static slots defined in content/contact.ts
 * so the slot picker renders identically. In live mode this would query the
 * business calendar for real availability.
 *
 * Currently returns the full slot list for every date — the live path should
 * filter by actual calendar free/busy status.
 */
export async function getAvailableSlots(
  _dateLabel: string,
): Promise<{ slots: readonly string[]; mode: 'live' | 'demo' }> {
  // Import inline to avoid a circular dep: content → lib → content.
  const { demoTimeSlots } = await import('@/content/contact')

  if (!isCalendarConfigured()) {
    return { slots: demoTimeSlots, mode: 'demo' }
  }

  // Live path: replace with real Google Calendar free/busy query.
  // For now fall back to the full list even in live mode until implemented.
  return { slots: demoTimeSlots, mode: 'live' }
}
