/**
 * ---------------------------------------------------------------------------
 * Calendar provider — Google Calendar + Google Meet integration.
 * Phase 8 Step 3 (complete implementation).
 *
 * Authentication: Service Account (JSON key via env vars).
 * This is the simplest server-to-server auth method for Google Workspace
 * calendars. No OAuth redirect or user consent is required.
 *
 * Environment contract (see .env.example):
 *   GOOGLE_CALENDAR_ID            — Calendar ID to create events on.
 *                                   Usually the primary team calendar email,
 *                                   e.g. demos@thewify.com
 *   GOOGLE_SERVICE_ACCOUNT_EMAIL  — Service account email from Google Cloud.
 *                                   e.g. unify-booking@project.iam.gserviceaccount.com
 *   GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY — RSA private key from the downloaded
 *                                   JSON key file. In .env.local, paste the
 *                                   -----BEGIN RSA PRIVATE KEY----- block as a
 *                                   single line with literal \n sequences, or
 *                                   use a multiline value (Next.js handles both).
 *
 * Mode contract:
 *   All three credentials present → live Google Calendar event + Meet link
 *   Any credential absent          → DEMO mode (nothing created, UI says so)
 *
 * Security:
 *   - This file is server-only. Never imported into client bundles.
 *   - Private key is read only at call time inside server functions.
 *   - Personal booking data is never logged.
 *   - Google API errors are sanitised before returning to the caller.
 * ---------------------------------------------------------------------------
 */

import { google } from 'googleapis'
import { buildIstDatetime, addMinutes } from './datetime'

// ---------------------------------------------------------------------------
// Shared types — unchanged so the demo-booking API route does not change.
// ---------------------------------------------------------------------------

export type CalendarBookingRequest = {
  /** Booker's display name. */
  name: string
  /** Booker's email — receives the calendar invite in live mode. */
  email: string
  /** Company or ISP name — included in the event title. */
  company: string
  /**
   * Date label from the slot picker ("Tomorrow" | "In 2 Days" | "Next Monday").
   * Resolved into a real calendar date in IST by buildIstDatetime().
   */
  date: string
  /** IST time slot string, e.g. "10:00 AM IST". */
  slot: string
}

export type CalendarBookingResult =
  | {
      ok: true
      mode: 'live'
      /** Google Calendar event ID — available for cancellation / rescheduling. */
      eventId: string
      /** Google Meet URL generated by the Calendar API. */
      meetUrl: string
      /** ISO 8601 datetime string for the booked slot in IST (UTC+5:30). */
      startsAt: string
    }
  | {
      ok: true
      mode: 'demo'
      reason: string
      /** Placeholder — real Meet links are only generated in live mode. */
      meetUrl: null
    }
  | {
      ok: false
      mode: 'live' | 'demo'
      error: string
    }

// ---------------------------------------------------------------------------
// Credential check — single source of truth.
// ---------------------------------------------------------------------------

function isCalendarConfigured(): boolean {
  return (
    typeof process.env['GOOGLE_CALENDAR_ID'] === 'string' &&
    process.env['GOOGLE_CALENDAR_ID'].length > 0 &&
    typeof process.env['GOOGLE_SERVICE_ACCOUNT_EMAIL'] === 'string' &&
    process.env['GOOGLE_SERVICE_ACCOUNT_EMAIL'].length > 0 &&
    typeof process.env['GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY'] === 'string' &&
    process.env['GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY'].length > 0
  )
}

// ---------------------------------------------------------------------------
// Service Account auth helper — creates a fresh auth client per request.
// No singleton — private key is read at call time on the server.
// ---------------------------------------------------------------------------

function buildAuth() {
  // The private key is stored in .env.local with literal \n sequences.
  // Replace them with real newlines so the PEM is valid for the JWT signer.
  const privateKey = (process.env['GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY'] as string).replace(
    /\\n/g,
    '\n',
  )

  return new google.auth.JWT({
    email: process.env['GOOGLE_SERVICE_ACCOUNT_EMAIL'] as string,
    key: privateKey,
    scopes: ['https://www.googleapis.com/auth/calendar'],
  })
}

// ---------------------------------------------------------------------------
// Conference request ID generator.
// Resend with the same requestId is idempotent — Google will return the same
// Meet link if the event was already created with that ID.
// ---------------------------------------------------------------------------

function buildConferenceRequestId(date: string, slot: string, email: string): string {
  // Simple deterministic ID from the booking triple — no UUID dependency.
  const raw = `${date}|${slot}|${email}`
  return raw
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '-')
    .slice(0, 64)
}

// ---------------------------------------------------------------------------
// Live booking path.
// ---------------------------------------------------------------------------

async function bookLive(request: CalendarBookingRequest): Promise<CalendarBookingResult> {
  const calendarId = process.env['GOOGLE_CALENDAR_ID'] as string

  const startsAt = buildIstDatetime(request.date, request.slot)
  const endsAt = addMinutes(startsAt, 30) // 30-minute demo session
  const conferenceRequestId = buildConferenceRequestId(request.date, request.slot, request.email)

  const auth = buildAuth()
  const calendar = google.calendar({ version: 'v3', auth })

  try {
    const response = await calendar.events.insert({
      calendarId,
      // conferenceDataVersion=1 triggers Meet link creation.
      conferenceDataVersion: 1,
      sendUpdates: 'all',
      requestBody: {
        summary: `Unify Wi-Fi Demo — ${request.company}`,
        description: [
          `Booker: ${request.name}`,
          `Email: ${request.email}`,
          `Company / ISP: ${request.company}`,
          `Preferred slot: ${request.date} at ${request.slot}`,
          '',
          'This event was created automatically by the Unify Wi-Fi booking form.',
        ].join('\n'),
        start: { dateTime: startsAt, timeZone: 'Asia/Kolkata' },
        end: { dateTime: endsAt, timeZone: 'Asia/Kolkata' },
        attendees: [{ email: request.email, displayName: request.name }],
        conferenceData: {
          createRequest: {
            requestId: conferenceRequestId,
            conferenceSolutionKey: { type: 'hangoutsMeet' },
          },
        },
        reminders: {
          useDefault: false,
          overrides: [
            { method: 'email', minutes: 60 },
            { method: 'popup', minutes: 15 },
          ],
        },
      },
    })

    const event = response.data

    // Extract the Meet link — the video entry point holds the meet.google.com URL.
    const entryPoints = event.conferenceData?.entryPoints ?? []
    const meetUrl =
      entryPoints.find(
        (ep: { entryPointType?: string | null }) => ep.entryPointType === 'video',
      )?.uri ?? null

    if (!event.id || !meetUrl) {
      console.error('[calendar:live] Event created but missing id or Meet URL:', event.id ?? 'null')
      return {
        ok: false,
        mode: 'live',
        error: 'Booking was recorded but the Meet link could not be generated. Please contact us directly.',
      }
    }

    return { ok: true, mode: 'live', eventId: event.id, meetUrl, startsAt }
  } catch (err) {
    // Never surface Google API internals to the visitor.
    const msg = err instanceof Error ? err.message : 'unknown'
    console.error('[calendar:live] Google Calendar API error:', msg)
    return {
      ok: false,
      mode: 'live',
      error: 'Could not create the calendar booking. Please try again or email us directly.',
    }
  }
}

// ---------------------------------------------------------------------------
// Public API — unchanged interface so the demo-booking route doesn't change.
// ---------------------------------------------------------------------------


/**
 * Book a demo slot.
 *
 * - Credentials absent  → DEMO mode (no network call, meetUrl is null)
 * - Credentials present → creates a real Google Calendar event with Meet link
 */
export async function bookDemoSlot(
  request: CalendarBookingRequest,
): Promise<CalendarBookingResult> {
  if (!isCalendarConfigured()) {
    console.log(
      '[calendar:demo] Credentials absent. Would book slot:',
      request.date,
      request.slot,
    )
    return {
      ok: true,
      mode: 'demo',
      reason:
        'GOOGLE_CALENDAR_ID, GOOGLE_SERVICE_ACCOUNT_EMAIL, and ' +
        'GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY are not configured. ' +
        'No calendar event was created and no Google Meet link was generated.',
      meetUrl: null,
    }
  }

  return bookLive(request)
}

/**
 * Returns the available time slots for a given date label.
 *
 * Demo mode mirrors the static slots from content/contact.ts.
 * Live mode falls back to the same list until a real free/busy query
 * is implemented (a separate task — slot availability filtering is not
 * part of Phase 8 Step 3).
 */
export async function getAvailableSlots(
  _dateLabel: string,
): Promise<{ slots: readonly string[]; mode: 'live' | 'demo' }> {
  const { demoTimeSlots } = await import('@/content/contact')

  if (!isCalendarConfigured()) {
    return { slots: demoTimeSlots, mode: 'demo' }
  }

  // Live path: return the same full list for now.
  // TODO(future): query Google Calendar free/busy to filter unavailable slots.
  return { slots: demoTimeSlots, mode: 'live' }
}
